name: Deploy App

on:

  push:
  
    branches:
    
      - dev
      
jobs:
  
    create-deploy-app:
    
      name: create deploy app
      
      runs-on: ubuntu-latest
      steps:
            - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e     
            - uses: actions/checkout@v3
            - name: Compile CSS dan Javascript
              run: |
                npm install
                npm run build
            - name: Configure PHP 8.1
              uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
              with:
                php-version: '8.0'
                extensions: mbstring, ctype, PDO, json
